### ISSUE TITLE
Warning: Pagination(...): React component classes must extend React.Component.

### ISSUE THREAD

**Issue by ingro** [vayser/react-js-pagination#1]
Hello, I wanted to try your paginator but I got this error, I'm running on React 0.14.3 if this can help and that's how I'm using it:

```javascript
<Pagination
  activePage={1}
  totalItemsCount={50}
  itemsCountPerPage={10}
  onChange={this.onPageClick.bind(this)}
/>
```

**Comment by vayser** [comment]
Hi, let me check, not sure that 0.14 React is supported, but it should be
quick to fix

**Comment by vayser** [comment]
Done

If you are using npm v2, just update react-js-pagination module, if it's v3 - update module and install peerDependencies manually

**Comment by ingro** [comment]
Thanks for the fast fix, now it working! :)
