### ISSUE TITLE
custom class doesn't work

### ISSUE THREAD

**Issue by msmolev** [vayser/react-js-pagination#10]
Looks like custom class name property doesn't work. It always resets to default, probably because of https://github.com/vayser/react-js-pagination/blob/master/dist/Pagination.js#L115 (even though there's a change here: https://github.com/vayser/react-js-pagination/blob/master/src/components/Pagination.js#L117)

Does latest version need to be re-published?

**Comment by mromanoff** [comment]
I have same issue. property 'innerClass' doesn't exist in source or dist in latest published npm package.

**Comment by vayser** [comment]
going to update npm package

**Comment by mromanoff** [comment]
@vayser Thank you for quick fix. It's confirmed. it fixed as of 'npm install react-js-pagination@2.0.1'
