### ISSUE TITLE
Disable first/prev page instead of hiding

### ISSUE THREAD

**Issue by raoulus** [vayser/react-js-pagination#12]
Hi,

I like this simple component, but I'd like to improve the UX by disabling first/prev pagination element instead of hiding it. By doing this, the pagination will not 'jump' and it has more or less a fix width.

This could be of course a configurable thing.

Let me know what you think. I could prepare a MR the next days.

Best,
Raoul

**Comment by vayser** [comment]
Hi, thank you for your issue. I agree that paginator have UX issue that you described. Feel free to create PR.

**Comment by raoulus** [comment]
Would it be ok to trash karma and use mocha/jsdom/enzyme instead?

**Comment by wagoid** [comment]
I wanted to make this change too, just forgot about that haha
@raoulus if you want help with anything let me know 😃

**Comment by vayser** [comment]
@raoulus it would be great

**Comment by raoulus** [comment]
Please review my PR https://github.com/vayser/react-js-pagination/pull/13

Sorry for the amount of changes, but I updated the dependencies and I also removed some unnecessary code.

@vayser You could setup travis-ci integration. Config is there.

**Comment by vayser** [comment]
@raoulus thank you for PR, apologize for late response. I will review all changes and merge with travis CI soon

**Comment by cslinmiso** [comment]
Hi @vayser thank you for this excellent lib, it really save my day.
However there's some minor issue that you might not notice, I hate to create a issue here so I took a liberty making some changes, PR #14 submitted.

It changes the way parameters input for custom element (nextPage...etc) and make it overridable.

Thank you!
