### ISSUE TITLE
Add possibility to hide first/last page buttons

### ISSUE THREAD

**Issue by crlcu** [vayser/react-js-pagination#17]
Hi,

Thanks for this nice package.

It would be very nice if you could add a `hideFirstPageLink` and `hideLastPageLink` options to this package - in order to make it possible to chose if you want to display or not these links.

**Comment by vayser** [comment]
Hi, probably i will add css classes to these buttons, it gives you ability to control appearance of them

**Comment by crlcu** [comment]
Hi,

That might be good as well.

**Comment by wagoid** [comment]
Closing this issue since it can be done with css 🙂 
We have the `itemClass` and `linkClass` properties now, you can also use those to target the first and last list items.
