### ISSUE TITLE
Hide pagination if items are less than itemsCountPerPage 

### ISSUE THREAD

**Issue by Shadowman4205** [vayser/react-js-pagination#18]
In version 2.0.1 the pagination is hiding if items<itemsCountPerPage, but in 2.0.2 it is showing unclikable pagination? Is this bug?

**Comment by vayser** [comment]
Hi, yes, seems it's a bug. Feel free to create PR, or i will fix it next week

**Comment by vayser** [comment]
@Shadowman4205 as quick fix you can pass `hideDisabled` property to <Pagination /> component

`<Pagination
  hideDisabled={itemsCountPerPage > totalItemsCount ? true: false }
  {...props}
/>`

**Comment by Shadowman4205** [comment]
@vayser Thank you very much!

**Comment by wagoid** [comment]
Actually it is a feature. You just need to set `hideDisabled` prop to `true`. When setting `hideDisabled` to false, it will add a `disabled` class to the `li`, when setting to `true`, it will not render the element, as in the previous behavior.
I think the best solution should be setting `hideDisabled` default value to `true`, that way this feature keeps backward compatible.
