### ISSUE TITLE
pageRangeDisplayed set to "1" does not display any page numbers

### ISSUE THREAD

**Issue by garettg** [vayser/react-js-pagination#21]
Looking to display only the current page number with next and previous buttons as the only way to navigate pages. Setting pageRangeDisplayed to 1 does not render any page numbers.

**Comment by mortenko** [comment]
Hi @garettg. The problem is that this implementation of paginator is using general algorithm for paginator (look at this http://deoxxa.github.io/paginator/), which has wrong implementation. it doesnt consider if pageRangeDisplayed is set up on 1 and I think it has problem if it set up also on two.

**Comment by samay3191** [comment]
FirstPage link is always disabled if I set pageRangeDisplayed={1}. Is there any workaround for this?

**Comment by vayser** [comment]
fixed at 3.0.0 version
