### ISSUE TITLE
It does not show 1 page when totalItemsCount is smaller than itemsCountPerPage.

### ISSUE THREAD

**Issue by hirokimoto** [vayser/react-js-pagination#24]
For instance,

<Pagination
            prevPageText='Prev'
            nextPageText='Next'
            activePage={props.activePage} 
            itemsCountPerPage={10} 
            totalItemsCount={5} 
            pageRangeDisplayed={props.rangeDisplayed}
            onChange={(value) => props.onPage(value)}
        />

In this case, the component has been rendered like the screenshot.

![screen shot 2017-05-13 at 2 57 10 am](https://cloud.githubusercontent.com/assets/22752054/26010486/02e3445a-3788-11e7-89f6-6101e5197353.png)

I think the component should display 1 page number.
Thanks,
Hiroki.

**Comment by vayser** [comment]
fixed in 3.0.0 version
