### ISSUE TITLE
In firefox/IE, while changing from one page to another, it looks like the page is being redirected

### ISSUE THREAD

**Issue by danivegamx** [vayser/react-js-pagination#25]
When you click on any page or in the next/previous button, it "jumps" as is being redirected to the same page, in other words, the window scroll is set to the top of the page.

This is happening on Firefox and IE only.

**Comment by wagoid** [comment]
Hello @danivegamx, thanks for your report! I tried to reproduce this issue with our examples but everything was fine. Can you provide an url to a pen so I can see the error?

**Comment by danivegamx** [comment]
Hi, It's a ´private project and unfortunatelly I can't share it.
I logged if the window is being resized and yes, it's behaviour is similar to the situation when you click and scroll to an specific id on the page (It always put the viewport on the pagination position)

**Comment by danivegamx** [comment]
Hi, I was using another stuff that caused that. Now, working as expected. Thanks
