### ISSUE TITLE
Add previousPageClass and nextPageClass

### ISSUE THREAD

**Issue by rmkpatchaa** [vayser/react-js-pagination#28]
Hi,

I am actually using your library and in my global CSS I have .prev and .next classes for styling navigation items.

But there is no option to specify the previous page and next page classes.

**Comment by wagoid** [comment]
Hello @rmkpatchaa! Thank you for your request.
This was released in [v2.3.0](https://github.com/vayser/react-js-pagination/releases/tag/v2.3.0), in this release we're also providing props to style "first" and "last" pages classes.
Closing this 🚀

**Comment by rmkpatchaa** [comment]
👍  Thanks. I will check that.
