### ISSUE TITLE
pageRangeDisplayed set to 1, disables the First_Page link

### ISSUE THREAD

**Issue by samay3191** [vayser/react-js-pagination#30]
FirstPage link is always disabled if I set pageRangeDisplayed={1}. Is there any workaround for this?

**Comment by wagoid** [comment]
Hey there!
Unfortunately that's currently not possible.
If you find that very important, we can add a new prop (e.g. `enableFirstPage`) and use it in this line: https://github.com/vayser/react-js-pagination/blob/master/src/components/Pagination.js#L114

Could you create the PR?

**Comment by vayser** [comment]
fixed in 3.0.0 version
