### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by Y-Taras** [vayser/react-js-pagination#31]
I installed package and tried to use it :
`import Pagination from 'react-js-pagination';
...
<Pagination />`
But got an error
![screenshot from 2017-09-16 19 52 51](https://user-images.githubusercontent.com/8538134/30514180-d9306d32-9b18-11e7-85a3-69b4e7014166.png)

**Comment by wagoid** [comment]
This is not related to this package :smiley:
This is probably because you are trying to use `babel-preset-2015` without having it installed.
You can get some info in this SO question: https://stackoverflow.com/questions/40188578/webpack-babel-couldnt-find-preset-es2015-relative-to-directory
