### ISSUE TITLE
React v16 dependency issue

### ISSUE THREAD

**Issue by austinh** [vayser/react-js-pagination#36]
My react dependency list in yarn shows react-js-pagination requiring react-js-pagination@15.6.1 when upgrading to react 16

Im getting errors about multiple copies of react installed.
 Run:

`yarn list react`

produces:

```
yarn list v1.1.0
├─ react-js-pagination@2.3.0
│  └─ react@15.6.1
└─ react@16.0.0
```

**Comment by vayser** [comment]
Hi, please update to latest version 3.0. There is React 16 in dependencies
