### ISSUE TITLE
Hide First Page / Last Page Elements

### ISSUE THREAD

**Issue by erwstout** [vayser/react-js-pagination#38]
Loving this so far, the only thing I wish I could do, and maybe I'm over looking something here, is to hide the First Page and Last Page elements and only show the Next Page / Prev Page elements. Is there a way to do so? If not it may be worth exploring. Thanks!

**Comment by vayser** [comment]
hi. thanks for asking. now there is no way to hide first/last pages. will be added with next update. now you can hide these buttons with css. 

`<Pagination linkClassLast='hidden' linkClassFirst='hidden' ... />`

`.hidden {
display: none;
}`

**Comment by sergioviniciuss** [comment]
Could you provide an actual example where data changes when pagination changes.. I'm struggling to deal with it.

**Comment by vayser** [comment]
![image](https://user-images.githubusercontent.com/1277505/32725738-e62274fc-c87e-11e7-9334-b2d6bfe62111.png)


![image](https://user-images.githubusercontent.com/1277505/32725719-d4c784ea-c87e-11e7-9eff-93c3924dac0a.png)

**Comment by francas** [comment]
@vayser the Pagination linkClassLast='hidden' does not work for me since it adds up to existing linkClass, while I believe it should be possible to define them separately.

Now my linkClass is `pagination-control`, and when I add linkClassLast='hidden', it becomes `pagination-control hidden`

**Comment by darol100** [comment]
@vayser,

This seems to be a requested feature for few folks (including myself). Do you think this will be added to the roadmap for this project?

Maybe add an option to set a state to hide this functionality?

**Comment by justinwilson-apollidon** [comment]
+1 for me as well.

**Comment by vayser** [comment]
added `hideFirstLastPages` property

**Comment by darol100** [comment]
Thanks @vayser

**Comment by erwstout** [comment]
Awesome thanks!!!
