### ISSUE TITLE
how to show total number of pages also in the end

### ISSUE THREAD

**Issue by sant527** [vayser/react-js-pagination#40]
how to show total number of pages also in the end

**Comment by anderpo** [comment]
<div className="row">
                                    <div className="col-md-3">
                                        <p className="text-info">
                                             Page {this.state.activePage} from {Math.ceil(this.state.totalItemsCount / this.state.itemsCountPerPage)}
                                        </p>
                                    </div>
                                </div>
![1](https://user-images.githubusercontent.com/6449432/32954628-b6ce04a2-cbc4-11e7-81c4-1327fefb7a21.png)

**Comment by vayser** [comment]
you can calculate total number by yourself

`Math.ceil(totalItemsCount / itemsCountPerPage)`


![image](https://user-images.githubusercontent.com/1277505/32960923-5ce8324a-cbcf-11e7-9ebb-6dcbb0e9fbef.png)
