### ISSUE TITLE
Allow defining disabled link class

### ISSUE THREAD

**Issue by francas** [vayser/react-js-pagination#42]
My classes are managed via links, not list item elements, so I would appreciate if additional param `disabledlinkClass` was available.

E.g. I don't need li class = disabled, but I need a class=disabled.

**Comment by vayser** [comment]
Hi, could you explain why `.disabled a` is not working for you

**Comment by francas** [comment]
Hello Kyle,

Thanks for getting in touch with us! I hope you are doing great today! :)

Could you please provide more info regarding your request?

Looking forward to your reply! :)

Regards,
Mindaugas B.


Hostinger Customer Service
http://www.hostinger.com

**Comment by francas** [comment]
I can't recall it at the moment as the project has passed.
