### ISSUE TITLE
Safari [Error] TypeError: Map constructor does not accept arguments

### ISSUE THREAD

**Issue by eric-personal** [vayser/react-js-pagination#43]
I'm getting the below error only in Safari. When I remove my import of react-js-pagination.js it goes away. It stops my entire site from loading locally in Safari. Anyone else having this issue or know how I can fix this ? 

Safari : Version 8.0.8
Mac OSX Yosemite V10.10.5
"webpack": "^2.2.1"

```
[Error] TypeError: Map constructor does not accept arguments
	Map (undefined, line 1013)
	(anonymous function)
	(anonymous function)
	eval code
	eval ([native code], line 0)
	(anonymous function) (bundle.js, line 6281)
	__webpack_require__ (bundle.js, line 660)........

```

**Comment by eric-personal** [comment]
Anyone out there can help with this issue ?

**Comment by wagoid** [comment]
Hello @eric-personal, sorry for the delay. The library does not use Map, and I looked at our dependencies to make sure (`classnames` and `paginator`) and they don't use it either. Is it possible to share with us a minimal demo that shows the error (using a tool like jsfiddle or webpackbin)?

**Comment by wagoid** [comment]
You can also try to see where this error is actually coming from (from your stack traces). Disabling the [devtool option](https://webpack.js.org/configuration/devtool/#devtool) in your webpack config might help getting around the weird `eval` calls 😃
