### ISSUE TITLE
Add possibility to configure the a href of every paginator

### ISSUE THREAD

**Issue by ioanlucut** [vayser/react-js-pagination#44]
Currently the href of every paginator is hard coded to be `#`, see https://github.com/vayser/react-js-pagination/blob/5a1b7ad6dd9766501b5cfb17873eb3fb10dc5d5c/src/components/Page.js#L65

Would be great to have a hook which configures the way how the href is rendered, useful e.g. for SEO crawlers.

Thanks!

**Comment by darol100** [comment]
@ioanlucut Are you doing service side rendering to your react components? If you are not doing SSR SEO crawlers will not be able to read it anyway.

**Comment by ioanlucut** [comment]
Yes, we're doing SSR.

Anyways, I'd be glad to provide a PR for it.

**Comment by darol100** [comment]
@ioanlucut , I will be more than happy to test out that PR.

**Comment by vayser** [comment]
added `getPageUrl` property

**Comment by djalmaaraujo** [comment]
@vayser I can't use this property, simply does not work. Using master instead of the last release.
