### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by prisar** [vayser/react-js-pagination#45]
I am getting this error when i am trying to import:

`Module not found: You attempted to import ../components/Pagination which falls outside of the project src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/.`

**Comment by vayser** [comment]
you should import in this way

`import Pagination from "react-js-pagintaion";`

please dont copy past README file

**Comment by prisar** [comment]
@vayser this works, but then it can also be updated in readme
