### ISSUE TITLE
Strange symbol

### ISSUE THREAD

**Issue by vomchik** [vayser/react-js-pagination#46]
Hi. I am using your library directly from the source but I got the error on compiling step. 

After inspecting your code I found this symbol `::` (https://github.com/vayser/react-js-pagination/blob/master/src/components/Page.js#L64).

What is it? it some magic for me. How can I fix it? Any idea?

**Comment by vayser** [comment]
Hi Valdemar, thanks for asking.

Please don't use `react-js-paginations` from source. It requires synchronize our build configuration with your own. Probably you don't need it. 

about `::` symbol you can read here: https://babeljs.io/docs/plugins/transform-function-bind/

**Comment by vomchik** [comment]
Oh, I see. Thank you very much.
