### ISSUE TITLE
getPageUrl not working

### ISSUE THREAD

**Issue by djalmaaraujo** [vayser/react-js-pagination#52]
```js
<Pagination
      activePage={actualPage}
      itemsCountPerPage={itemsCountPerPage}
      totalItemsCount={totalItemsCount}
      pageRangeDisplayed={5}
      itemClass='page-item'
      activeLinkClass='page-link active'
      linkClass='page-link'
      onChange={(nextPage) => paginateHandler(searchParams, nextPage)}
      getPageUrl={(i) => `/the-url/${i}`}
    />
```

this is not returning the url.. a bug? I still get '#'

**Comment by djalmaaraujo** [comment]
I think you forgot to generate a release with the latest features @vayser

**Comment by b0ff1n** [comment]
confirming. getPageUrl is not called in 3.0.1

**Comment by carlo-fontanos** [comment]
The author indeed forgot to rebuild. 

If you check the source it's in there. So you just rebuild it to update the contents of **dist** folder. 
I rebuild it and now the **getPageUrl()** is working.

**Comment by djalmaaraujo** [comment]
@carlo-fontanos while this is a workaround, will not work for auto-deployments, only if you commit the node_modules. I think the best solution now would be using a fork, maybe?

**Comment by djalmaaraujo** [comment]
@vayser can you rebuild and generate a new release?

**Comment by sag1v** [comment]
@vayser Why is his closed, did you publish these changes? 
Seems like `getPageUrl` still not supported on latest version
