### ISSUE TITLE
Bootstrap 4 Compatibility - (Not a huge issue)

### ISSUE THREAD

**Issue by cmakohon** [vayser/react-js-pagination#53]
First off, I love this component! By my estimation this tool currently only supports Bootstrap 3.x. If you would like it to work for Bootstrap 4, you will need to add 2 additional props when using this component:

itemClass="page-item"
linkClass="page-link"

**Comment by windhamwong** [comment]
Works perfectly. Why not creating a PR for this?

**Comment by Braj65** [comment]
God. This was so helpful. Wasted 2 hrs then landed on this.

**Comment by vayser** [comment]
I am not forcing anyone to use react-js-pagination with bootstrap. It is just compatible with bootstrap and you can integrate it into any bootstrap project with 0 configuration.

about `require("bootstrap/less/bootstrap.less");` this is just a line from example, the way how I imported bootstrap styles into example. You need to add `less-loader` to the webpack config to make example works.

But, you can add bootstrap styles in any other way: 
`import 'bootstrap/dist/css/bootstrap.min.css';`
or
`<link rel="stylesheet" href="path-to-bootstrap.css">`

**Comment by hariDasu** [comment]
thanks, @vayser i did ultimatly end up using the less-loader in my webpack config and it worked with this line

**Comment by souuu** [comment]
> Works perfectly with `reactstrap` library. Why not create a PR for this?
> I don't mind if you want me to create a PR for you.

Can you explain how you make it works with reactstrap please ?

**Comment by vayser** [comment]
@cmakohon thank you for your comment, I'm going to add it to README
