### ISSUE TITLE
Not clear how to use it

### ISSUE THREAD

**Issue by ilyasogonov** [vayser/react-js-pagination#54]
Hi! Thank you for the plugin. I managed to add the component to the app, though I cannot figure out how to pass the data to show. How does the Pagination component know what items to display? Should I decorate the list of items with it?

**Comment by davidalejandroaguilar** [comment]
This component **only generates markup** based on the total items. There are only 3 required props: `totalItemsCount`, `activePage` and an `onChange` handler.

To display things, just have your component display things based on the `activePage`:

```js
import React from 'react';
import Pagination from 'react-js-pagination';

const THINGS_PER_PAGE = 5;

export default class Things extends React.Component {
  state = {
    activePage: 1,
    things: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  };

  // Just set the active page on state on page change.
  handlePageChange = pageNumber => this.setState({ activePage: pageNumber });

  render() {
    // Things shown will be calculated based on active page.
    const indexOfLastThing = this.state.activePage * THINGS_PER_PAGE;
    const indexOfFirstThing = indexOfLastThing - THINGS_PER_PAGE;
    // For page 1, you will get things.slice(0, 5).
    // For page 2, you will get things.slice(5, 10).
    const thingsShown = this.state.things.slice(
      indexOfFirstThing,
      indexOfLastThing
    );

    // Then just show the things.
    return (
      <div>
        <ul>
          {thingsShown.map((thing, index) => (
            <li key={index}>{thing}</li>
          ))}
        </ul>

        <Pagination
          onChange={this.handlePageChange}
          activePage={this.state.activePage}
          totalItemsCount={this.state.things.length}
          itemsCountPerPage={5}
        />
      </div>
    );
  }
}
```

Ideally, you'd want to separate your component from containers, but this is just a mixed example for you to see the general idea.

**Comment by Ruchit1395** [comment]
for the same code, line to line, I'm getting this results. CSS not working.
![Screenshot from 2019-09-23 18-44-42](https://user-images.githubusercontent.com/25167877/65429880-8d316100-de34-11e9-9d1a-d58af1481e61.png)

**Comment by davidalejandroaguilar** [comment]
Hey there, as I said:

>this component only generates markup

There's no CSS, you have to write that yourself. The first page of the package itself states it too:

>The component comes with no built-in styles
