### ISSUE TITLE
How to know when prev button is pressing and when next button is pressing?

### ISSUE THREAD

**Issue by sutriptaroy** [vayser/react-js-pagination#59]
I need to increase or decrease the page no according to prev or next. so it is needed to idetify which button is pressing. please help me.

**Comment by sutriptaroy** [comment]
_handlePageChange(pageNumber) {
    console.log(`active page is ${pageNumber}`);
    this.setState({activePage: pageNumber});
  }

the pageNumber argument is helping with this issue. thanks for this library. Helped a lot.

**Comment by vayser** [comment]
you are welcome
