### ISSUE TITLE
There are lots of mistakes in the work!!!really can't stand!!!

### ISSUE THREAD

**Issue by aljazeeras** [vayser/react-js-pagination#6]
There are lots of mistakes in the work!!!really can't stand!!!

**Comment by vayser** [comment]
you can create pull request with fixes or at least provide more details about issues

**Comment by sabov** [comment]
@aljazeeras don't create useless issues If you found a bug you can always report it or even more - provide a fix. This is an open source project and you have to respect other members who is doing something for entire community.
