### ISSUE TITLE
Component adds an extra page number

### ISSUE THREAD

**Issue by ancagiurgiu** [vayser/react-js-pagination#60]
Component adds an extra page number when totalItemsCount does not divide exactly itemsCountPerPage.
For example, if totalItemsCount is 383 and itemsCountPerPage is 10, there should be 39 pages displayed, but component renders 37 pages with 10 items, page 38 contains 3 items and page 39 is empty.

**Comment by vayser** [comment]
@ancagiurgiu Hi. 38 pages can display 380 items. But you have 383 item. So you need another one page to display 3 extra item

**Comment by ancagiurgiu** [comment]
Yes, you're right. Sorry, the behavior is different. I expected to have 38 pages, each of them containing 10 items, but it renders 37 pages with 10 items, 38 page contains only 3 items, and page 39 is empty.

**Comment by ancagiurgiu** [comment]
It seems it was a backend issue. It works perfectly now. Thanks a lot!
