### ISSUE TITLE
What's the difference between react-paginate?

### ISSUE THREAD

**Issue by Malavos** [vayser/react-js-pagination#62]
So, checking our project dependencies, we saw another project, [very close looking to this one.](https://www.npmjs.com/package/react-paginate). What's the difference between this project and that one?  Are they related?

Seems like react-paginate has been receiving some updates, and it begged the question.

Anyway, thanks!

**Comment by vayser** [comment]
Hi, these are two independent projects with different contributors. Not related to each other

**Comment by Malavos** [comment]
@vayser  alright, thank you very much for the clarification. Cheers, mate!
