### ISSUE TITLE
TypeError: this.props.onClick is not a function

### ISSUE THREAD

**Issue by Natanagar** [vayser/react-js-pagination#63]
In Page.js after event (click) in devtools I see error:
`"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _createClass=function(){function e(e,t){for(var r=0;r<t.length;r++){var a`
and handler was implented as `onChange={handlePageChange}` not as in desription `onChange={:: this.handlePageChange}`

Maybe I'm doing something wrong.

**Comment by Max-Zviagintsev** [comment]
+1

**Comment by Natanagar** [comment]
That is I see, maintainers don't resolve this problem yet.

**Comment by vayser** [comment]
please provide more details. I just checked, everything is working for me.

try:
` git clone git@github.com:vayser/react-js-pagination.git`
`cd react-js-pagination`
`npm i`
`npm start`

go to localhost:8000, works well for me, without errors which you mentioned above

**Comment by neilmaledev** [comment]
I also experienced the same exact error

dist/Pages.js line 73:
 
e.preventDefault(), r || this.props.onClick(a);

**Comment by neilmaledev** [comment]
BTW, I resolved this error on my end by doing this

constructor(props) {
    super();

    this.handlePageChange = this.handlePageChange.bind(this);
  }

handlePageChange(pageNumber) {
    console.log(`active page is ${pageNumber}`);
    this.setState({activePage: pageNumber});
  }


<Paginate ... 
onChange={ this.handlePageChange }
/>

**Comment by neilmaledev** [comment]
Sorry my answer is not in a neat format.. ^^ but hope that can help somehow

**Comment by vayser** [comment]
@neilmaledev you are right. I have updated readme to avoid such issues at the future
