### ISSUE TITLE
go back to top after page change

### ISSUE THREAD

**Issue by tfmcunha** [vayser/react-js-pagination#69]
So, I have a component getting photos from an API.. I have react-js-pagination working and also added TransitionGroup and CSSTransition to animate the rendering.
But when changing page, there's a gap between the pagination and the photo container, and since the window focus is on the pagination, the animation is not seen and then the gap is closed suddenly.

Is it possible to get the focus back to the top of the page?

Thanks

**Comment by RukkiesMan** [comment]
Try `window.scrollTo(0, 0);`
