### ISSUE TITLE
CSS not implemented with latest bootstrap version

### ISSUE THREAD

**Issue by Puneetbh** [vayser/react-js-pagination#70]
Pagination design not working properly with latest bootstrap version, because it removed old classes

**Comment by HenriEl** [comment]
Ran across the same issue.

Turns out you can just add these props to the component to make it working:

`itemClass="page-item"
  linkClass="page-link"`

**Comment by vayser** [comment]
you can override any class. By default `react-js-pagination` compatible with Bootstrap 3. I'm thinking to switch to Bootstrap 4 at the further major version
