### ISSUE TITLE
Active class not being added 

### ISSUE THREAD

**Issue by AWR14** [vayser/react-js-pagination#72]
reopening this https://github.com/vayser/react-js-pagination/issues/37

Anyone else had this issue and found a solution or idea why its doing it?

**Comment by ChocolateSlayer** [comment]
For me this didn't work when I passed String value to the activePage property.

>  <Pagination
          activePage={"1"}  //Doesn't work
          activeLinkClass="pagination__link pagination__link_active"/>

> <Pagination
          activePage={Number("1")}  // Works well
          activeLinkClass="pagination__link pagination__link_active"/>

**Comment by sleyderzm** [comment]
> For me this didn't work when I passed String value to the activePage property.
> 
> > <Pagination
> > activePage={"1"}  //Doesn't work
> > activeLinkClass="pagination__link pagination__link_active"/>
> 
> > <Pagination
> > activePage={Number("1")}  // Works well
> > activeLinkClass="pagination__link pagination__link_active"/>

i have the same issue and work parsing to Number, thanks a lot
