### ISSUE TITLE
Getting errors related to 'classProperties'

### ISSUE THREAD

**Issue by dayanfcosta** [vayser/react-js-pagination#79]
Hi,

I'm trying to use this lib on a personal project but when I use the Pagination component, automatically I get the following error:

![image](https://user-images.githubusercontent.com/8143786/63215974-12cf3c00-c126-11e9-9cbe-8e985bb85acd.png)

I have added the babel plugin in my package.json as show below, but I still getting this error.
![image](https://user-images.githubusercontent.com/8143786/63215942-b5d38600-c125-11e9-8512-8fb0429275c5.png)
![image](https://user-images.githubusercontent.com/8143786/63215944-c552cf00-c125-11e9-8e5a-7c5141b1bf82.png)

May someone help me?

**Comment by vayser** [comment]
Please use compiled version of `react-js-pagination`
