### ISSUE TITLE
CSS not working 

### ISSUE THREAD

**Issue by Ruchit1395** [vayser/react-js-pagination#85]
Page is displaying very rudimentary style. The one shown in demo is not working.

![Screenshot from 2019-09-23 18-44-42](https://user-images.githubusercontent.com/25167877/65429465-d7661280-de33-11e9-9e84-cb121d8daedb.png)

**Comment by vayser** [comment]
react-js-pagination provides just markup. you have to wire css by yourself.
I agree, this is a bad design. I think I will remove classes for the next version and apply some default styles
